#!/bin/bash

# setup-adl - Setup AMD ADL SDK for usage in amdinfo
# Copyright (C) 2016 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>

if [[ -z "${1:-}" ]]; then
	echo "Setup AMD ADL SDK for usage in amdinfo"
	echo "Usage: ${0##*/} <ADL_SDK_DIR>"
	exit
fi >&2

ADL_SDK=$1

mydir=$(dirname "$(readlink -f "$0")")
target="$mydir"/ADL_SDK

if ! [[ -d "$ADL_SDK" ]]; then
	echo "AMD ADL SDK not found in: $ADL_SDK"
	exit
fi >&2


rm -f -- "$target" &&
ln -s -- "$ADL_SDK" "$target" &&
grep -q '}ADLErrorInjection;;' -- "$target"/include/adl_structures.h &&
sed -i '/^[ \t]*}ADLErrorInjection;;/s/;;/;/' -- "$target"/include/adl_structures.h
